name: GodItems
version: '${project.version}'
main: com.oxide.goditems.GodItems
api-version: '1.21'
author: Oxide
description: God Trident + Thunder Crossbow custom abilities.

commands:
  goditems:
    description: GodItems main command
    usage: /goditems give <trident|crossbow> [player]
    aliases: [gi, gitems]

permissions:
  goditems.give:
    description: Custom items lene ki permission
    default: op
  goditems.reload:
    description: Config reload
    default: op
  goditems.use.trident:
    description: God Trident ability use
    default: true
  goditems.use.crossbow:
    description: Thunder Crossbow ability use
    default: true
  goditems.bypass:
    description: Abilities se immune
    default: false
  goditems.cooldown.bypass:
    description: Cooldown bypass
    default: op
